# Generated by Django 3.1.6 on 2021-02-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('token', models.TextField(max_length=4, primary_key=True, serialize=False, verbose_name='Token')),
                ('number_visits', models.TextField(default=0, verbose_name='Number of visits')),
                ('active', models.BooleanField(default=True, verbose_name='Activate')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
